# Generated by Django 5.0.2 on 2024-02-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('useremail', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
