# Generated by Django 5.0.2 on 2024-03-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_contact_useremail_alter_contact_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='myimage',
            field=models.ImageField(blank=True, null=True, upload_to='usermedia'),
        ),
    ]
